version: "3.2"
services:
  nginx:
      image: nginx:latest
      container_name: 'nginx'
      restart: always
      network_mode: host
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/letsencrypt/:/etc/letsencrypt/
        - /etc/ssl/certs:/etc/ssl/certs
        